systemProp.sonar.host.url=http://localhost:9000
systemProp.sonar.projectKey=Csv-writer
systemProp.sonar.projectName=Csv-writer library
systemProp.sonar.token=squ_b5f679133764b0c8b6acc6456985df489522849a

fakerLibVersion=1.0.2
mockitoCoreVersion=5.20.0
jupiterPomVersion=5.10.0

projectVersion=1.0-SNAPSHOT
